sudo: required
language: generic
dist: xenial 

addons:
  apt:
    packages:
      libc6-i386
      libspeexdsp-dev
      libsamplerate0-dev
      sox
      git
      libwxgtk3.0-dev portaudio19-dev libhamlib-dev libasound2-dev libao-dev libgsm1-dev libsndfile-dev
      
script:
    - ./build_ubuntu.sh
